=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::AttributesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AttributesApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::AttributesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AttributesApi' do
    it 'should create an instance of AttributesApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::AttributesApi)
    end
  end

  # unit tests for api_v2_attributes_entity_type_get
  # Get attribute definitions
  # @param entity_type 
  # @param [Hash] opts the optional parameters
  # @return [Array<AttributeDefinitionDto>]
  describe 'api_v2_attributes_entity_type_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_attributes_get
  # Get attribute definitions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :entity_type 
  # @return [Array<AttributeDefinitionDto>]
  describe 'api_v2_attributes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_attributes_groups_get
  # Get list of attribute group definitions
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :query 
  # @return [Array<AttributeGroupDefinitionDto>]
  describe 'api_v2_attributes_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_attributes_groups_name_get
  # Get attribute group definition
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [AttributeGroupDefinitionDto]
  describe 'api_v2_attributes_groups_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
