=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::EhrApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EhrApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::EhrApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EhrApi' do
    it 'should create an instance of EhrApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::EhrApi)
    end
  end

  # unit tests for api_v2_ehr_order_post
  # Create order HL7 (JSON)
  # @param [Hash] opts the optional parameters
  # @option opts [CreateOrderFromHl7Command] :create_order_from_hl7_command 
  # @return [ORRO02]
  describe 'api_v2_ehr_order_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_ehr_results_get
  # Get results by PlacerOrderNumber or FillerOrderNumber
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sending_facility 
  # @option opts [String] :placer_order_number 
  # @option opts [String] :filler_order_number 
  # @return [ORUR01]
  describe 'api_v2_ehr_results_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
