=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::FulfillmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FulfillmentsApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::FulfillmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FulfillmentsApi' do
    it 'should create an instance of FulfillmentsApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::FulfillmentsApi)
    end
  end

  # unit tests for api_v2_fulfillments_actions_get_shipping_options_post
  # Get Shipping Options
  # @param [Hash] opts the optional parameters
  # @option opts [GetAvailableShippingOptionsQuery] :get_available_shipping_options_query 
  # @return [GetAvailableShippingOptionsShippingOptionsResponseDto]
  describe 'api_v2_fulfillments_actions_get_shipping_options_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_fulfillments_actions_update_shipment_address_post
  # Edit Address for Shipment
  # @param [Hash] opts the optional parameters
  # @option opts [EditAddressCommand] :edit_address_command 
  # @return [EditAddressCommand]
  describe 'api_v2_fulfillments_actions_update_shipment_address_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_fulfillments_get
  # Get fulfillments
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_line_id 
  # @option opts [String] :order_id 
  # @option opts [String] :fulfillment_id 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @return [GetFulfillmentsFulfillmentDtoPaginatedList]
  describe 'api_v2_fulfillments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_fulfillments_id_delete
  # Cancel fulfillment
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_fulfillments_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
