=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::KitOrderLinesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KitOrderLinesApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::KitOrderLinesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KitOrderLinesApi' do
    it 'should create an instance of KitOrderLinesApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::KitOrderLinesApi)
    end
  end

  # unit tests for api_v2_kitorderlines_delete
  # Cancel a specific kit order line
  # @param [Hash] opts the optional parameters
  # @option opts [CancelKitOrderLine] :cancel_kit_order_line 
  # @return [nil]
  describe 'api_v2_kitorderlines_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kitorderlines_download_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :kit_numbers 
  # @option opts [String] :order_id 
  # @option opts [String] :order_line_id 
  # @option opts [String] :status 
  # @option opts [String] :attribute_term 
  # @option opts [String] :attributes_to_search 
  # @option opts [String] :attributes_filter 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @option opts [String] :order_by 
  # @option opts [String] :product_type 
  # @option opts [Boolean] :order_by_asc 
  # @return [nil]
  describe 'api_v2_kitorderlines_download_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kitorderlines_get
  # Get the combinations of kit and associated orderline
  # @param [Hash] opts the optional parameters
  # @option opts [String] :kit_numbers 
  # @option opts [String] :order_id 
  # @option opts [String] :order_line_id 
  # @option opts [String] :status 
  # @option opts [String] :attribute_term 
  # @option opts [String] :attributes_to_search 
  # @option opts [String] :attributes_filter 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @option opts [String] :order_by 
  # @option opts [String] :product_type 
  # @option opts [Boolean] :order_by_asc 
  # @return [GetKitOrderLinesKitOrderLineDtoPaginatedList]
  describe 'api_v2_kitorderlines_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kitorderlines_kits_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :kit_numbers 
  # @option opts [String] :order_id 
  # @option opts [String] :order_line_id 
  # @option opts [String] :status 
  # @option opts [String] :attribute_term 
  # @option opts [String] :attributes_to_search 
  # @option opts [String] :attributes_filter 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @option opts [String] :order_by 
  # @option opts [String] :product_type 
  # @option opts [Boolean] :order_by_asc 
  # @return [nil]
  describe 'api_v2_kitorderlines_kits_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
