=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::KitsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KitsApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::KitsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KitsApi' do
    it 'should create an instance of KitsApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::KitsApi)
    end
  end

  # unit tests for api_v2_kits_actions_kit_number_upload_documents_document_type_post
  # Upload Kits Documents
  # Image or Text File only
  # @param kit_number Kit Number
  # @param document_type ClinicIntake, DriversLicense, Insurance, KitDocument, KitRequisitionForm, MedicalNecessity, ReleaseForm
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_actions_kit_number_upload_documents_document_type_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_actions_upload_kit_attributes_csv_post
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_actions_upload_kit_attributes_csv_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_get
  # Get kits
  # OrderNumber &#x3D; Parent OrderId  Status &#x3D; Error, Canceled, Not Received, Received, In Lab, Completed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :kit_number 
  # @option opts [String] :order_number 
  # @option opts [String] :status 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @return [GetKitsKitsOrdersDtoPaginatedList]
  describe 'api_v2_kits_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_attribute_attribute_name_delete
  # Delete kit single attribute
  # @param attribute_name 
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_kit_number_attribute_attribute_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_attributes_delete
  # Delete kit attributes
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_kit_number_attributes_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_attributes_namevalue_patch
  # Set kit attribute
  # @param kit_number 
  # @param name 
  # @param value 
  # @param [Hash] opts the optional parameters
  # @return [KitAttributeValueDto]
  describe 'api_v2_kits_kit_number_attributes_namevalue_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_attributes_patch
  # Set kit attributes
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @option opts [SetKitAttributeValues] :set_kit_attribute_values The kitnumber and attributes name,value pairs
  # @return [Array<KitAttributeValueDto>]
  describe 'api_v2_kits_kit_number_attributes_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_delete
  # Cancel the kit including the order line items.
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_kit_number_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_gender_gender_patch
  # Set kit gender
  # @param kit_number 
  # @param gender 
  # @param [Hash] opts the optional parameters
  # @return [KitSummaryDto]
  describe 'api_v2_kits_kit_number_gender_gender_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_get
  # Get kit by kit number
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [KitDto]
  describe 'api_v2_kits_kit_number_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_order_lines_delete
  # Cancel the kit including the order line items.
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_kits_kit_number_order_lines_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_orders_get
  # Get orders associated with a specific kit
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [KitsOrdersDto]
  describe 'api_v2_kits_kit_number_orders_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_kits_kit_number_results_get
  # Get kit order line results associated with a specific kit
  # @param kit_number 
  # @param [Hash] opts the optional parameters
  # @return [KitResultsDto]
  describe 'api_v2_kits_kit_number_results_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
