=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::NotificationSubscriptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NotificationSubscriptionsApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::NotificationSubscriptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationSubscriptionsApi' do
    it 'should create an instance of NotificationSubscriptionsApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::NotificationSubscriptionsApi)
    end
  end

  # unit tests for api_v2_notification_subscriptions_get
  # Get notification subscriptions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type 
  # @return [Array<NotificationSubscriptionDto>]
  describe 'api_v2_notification_subscriptions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_id_actions_reset_secret_post
  # Reset webhook secret
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [NotificationSubscriptionDto]
  describe 'api_v2_notification_subscriptions_id_actions_reset_secret_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_id_delete
  # Unsubscribe from events
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_notification_subscriptions_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_id_get
  # Get notification subscription by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [NotificationSubscriptionDto]
  describe 'api_v2_notification_subscriptions_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_id_patch
  # Update notification subscription
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateNotificationSubscriptionCommand] :update_notification_subscription_command 
  # @return [NotificationSubscriptionDto]
  describe 'api_v2_notification_subscriptions_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_post
  # Subscribe to events
  # @param [Hash] opts the optional parameters
  # @option opts [CreateNotificationSubscriptionCommand] :create_notification_subscription_command 
  # @return [NotificationSubscriptionDto]
  describe 'api_v2_notification_subscriptions_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_notification_subscriptions_user_id_tenant_tenant_id_get
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v2_notification_subscriptions_user_id_tenant_tenant_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
