=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeneByGene::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = GeneByGene::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(GeneByGene::OrdersApi)
    end
  end

  # unit tests for api_v2_orders_actions_create_order_for_existing_kits_post
  # Create order for the given existing kit numbers
  # @param [Hash] opts the optional parameters
  # @option opts [CreateOrderForExistingKits] :create_order_for_existing_kits 
  # @return [OrderDto]
  describe 'api_v2_orders_actions_create_order_for_existing_kits_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_orders_get
  # Get orders
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_id 
  # @option opts [Time] :order_date_min 
  # @option opts [Time] :order_date_max 
  # @option opts [String] :product_name 
  # @option opts [Integer] :offset 
  # @option opts [Integer] :page_size 
  # @return [GetOrdersOrderDtoPaginatedList]
  describe 'api_v2_orders_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_orders_id_get
  # Get order by ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [OrderDto]
  describe 'api_v2_orders_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_orders_post
  # Create order
  # @param [Hash] opts the optional parameters
  # @option opts [CreateOrder] :create_order 
  # @return [OrderDto]
  describe 'api_v2_orders_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
