=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GeneByGene::GetAvailableShippingOptionsShippingOptionsResponseDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GeneByGene::GetAvailableShippingOptionsShippingOptionsResponseDto do
  let(:instance) { GeneByGene::GetAvailableShippingOptionsShippingOptionsResponseDto.new }

  describe 'test an instance of GetAvailableShippingOptionsShippingOptionsResponseDto' do
    it 'should create an instance of GetAvailableShippingOptionsShippingOptionsResponseDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GeneByGene::GetAvailableShippingOptionsShippingOptionsResponseDto)
    end
  end

  describe 'test attribute "duties_and_taxes_included"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error_messages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_options"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
