=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GeneByGene::GetKitsKitsOrdersDtoPaginatedList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GeneByGene::GetKitsKitsOrdersDtoPaginatedList do
  let(:instance) { GeneByGene::GetKitsKitsOrdersDtoPaginatedList.new }

  describe 'test an instance of GetKitsKitsOrdersDtoPaginatedList' do
    it 'should create an instance of GetKitsKitsOrdersDtoPaginatedList' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GeneByGene::GetKitsKitsOrdersDtoPaginatedList)
    end
  end

  describe 'test attribute "offset"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "page_size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
