=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GeneByGene::ORMO01PATIENTVISIT
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GeneByGene::ORMO01PATIENTVISIT do
  let(:instance) { GeneByGene::ORMO01PATIENTVISIT.new }

  describe 'test an instance of ORMO01PATIENTVISIT' do
    it 'should create an instance of ORMO01PATIENTVISIT' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GeneByGene::ORMO01PATIENTVISIT)
    end
  end

  describe 'test attribute "patient_visit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "patient_visit_additional_information"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
