=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GeneByGene::ORMO01OBSERVATION
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GeneByGene::ORMO01OBSERVATION do
  let(:instance) { GeneByGene::ORMO01OBSERVATION.new }

  describe 'test an instance of ORMO01OBSERVATION' do
    it 'should create an instance of ORMO01OBSERVATION' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GeneByGene::ORMO01OBSERVATION)
    end
  end

  describe 'test attribute "observation_segment"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "notes_and_comments"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
