=begin
#Nucleus API v2.0

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'gene_by_gene/api_client'
require 'gene_by_gene/api_error'
require 'gene_by_gene/version'
require 'gene_by_gene/configuration'

# Models
require 'gene_by_gene/models/add_kit_result_command'
require 'gene_by_gene/models/add_kit_result_command_kit_result'
require 'gene_by_gene/models/address_dto'
require 'gene_by_gene/models/attribute_definition_dto'
require 'gene_by_gene/models/attribute_group_definition_dto'
require 'gene_by_gene/models/attribute_group_dto'
require 'gene_by_gene/models/ce'
require 'gene_by_gene/models/cq'
require 'gene_by_gene/models/cx'
require 'gene_by_gene/models/cancel_kit_order_line'
require 'gene_by_gene/models/cancel_kit_order_line_item'
require 'gene_by_gene/models/courier_dto'
require 'gene_by_gene/models/courier_service_dto'
require 'gene_by_gene/models/create_notification_subscription_command'
require 'gene_by_gene/models/create_order'
require 'gene_by_gene/models/create_order_for_existing_kits'
require 'gene_by_gene/models/create_order_for_existing_kits_item'
require 'gene_by_gene/models/create_order_from_hl7_command'
require 'gene_by_gene/models/create_order_item'
require 'gene_by_gene/models/create_order_sample'
require 'gene_by_gene/models/create_order_shipment'
require 'gene_by_gene/models/dg1'
require 'gene_by_gene/models/err'
require 'gene_by_gene/models/edit_address_command'
require 'gene_by_gene/models/error_dto'
require 'gene_by_gene/models/fulfillment_dto'
require 'gene_by_gene/models/gt1'
require 'gene_by_gene/models/get_available_shipping_options_query'
require 'gene_by_gene/models/get_available_shipping_options_shipping_option_dto'
require 'gene_by_gene/models/get_available_shipping_options_shipping_options_response_dto'
require 'gene_by_gene/models/get_fulfillments_fulfillment_dto_paginated_list'
require 'gene_by_gene/models/get_kit_order_lines_kit_order_line_dto_paginated_list'
require 'gene_by_gene/models/get_kits_kits_orders_dto_paginated_list'
require 'gene_by_gene/models/get_order_line_item_by_guid_kit_status_summary'
require 'gene_by_gene/models/get_order_line_item_by_guid_result'
require 'gene_by_gene/models/get_order_line_item_by_guid_sibling_order_line'
require 'gene_by_gene/models/get_order_line_kits_by_line_guid_order_line_kit'
require 'gene_by_gene/models/get_order_line_kits_by_line_guid_result'
require 'gene_by_gene/models/get_orders_order_dto_paginated_list'
require 'gene_by_gene/models/in1'
require 'gene_by_gene/models/i_paginated_list1_nucleus_domain_features_results_result_kit_status_dto_nucleus_domain_version1000_cultureneutral_public_key_tokennull'
require 'gene_by_gene/models/key_value_pair2_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e'
require 'gene_by_gene/models/kit_attribute_value_dto'
require 'gene_by_gene/models/kit_dto'
require 'gene_by_gene/models/kit_order_dto'
require 'gene_by_gene/models/kit_order_line_dto'
require 'gene_by_gene/models/kit_order_line_result_dto'
require 'gene_by_gene/models/kit_order_line_status_dto'
require 'gene_by_gene/models/kit_order_line_statuses_dto'
require 'gene_by_gene/models/kit_results_dto'
require 'gene_by_gene/models/kit_summary_dto'
require 'gene_by_gene/models/kits_orders_dto'
require 'gene_by_gene/models/msa'
require 'gene_by_gene/models/msh'
require 'gene_by_gene/models/nte'
require 'gene_by_gene/models/name_value_pair2_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e'
require 'gene_by_gene/models/notification_subscription_dto'
require 'gene_by_gene/models/obr'
require 'gene_by_gene/models/obx'
require 'gene_by_gene/models/orc'
require 'gene_by_gene/models/ormo01_insurance'
require 'gene_by_gene/models/ormo01_observation'
require 'gene_by_gene/models/ormo01_order'
require 'gene_by_gene/models/ormo01_orderdetail'
require 'gene_by_gene/models/ormo01_orderdetailsegment'
require 'gene_by_gene/models/ormo01_patient'
require 'gene_by_gene/models/ormo01_patientvisit'
require 'gene_by_gene/models/orro02'
require 'gene_by_gene/models/orur01'
require 'gene_by_gene/models/orur01_observation'
require 'gene_by_gene/models/orur01_orderobservation'
require 'gene_by_gene/models/orur01_patient'
require 'gene_by_gene/models/orur01_patientresult'
require 'gene_by_gene/models/orur01_visit'
require 'gene_by_gene/models/order_dto'
require 'gene_by_gene/models/order_line_dto'
require 'gene_by_gene/models/pd1'
require 'gene_by_gene/models/pid'
require 'gene_by_gene/models/pv1'
require 'gene_by_gene/models/problem_details'
require 'gene_by_gene/models/product_dto'
require 'gene_by_gene/models/product_dto_component'
require 'gene_by_gene/models/result_kit_status_dto'
require 'gene_by_gene/models/results_status_list_dto'
require 'gene_by_gene/models/root'
require 'gene_by_gene/models/set_kit_attribute_values'
require 'gene_by_gene/models/shipment_dto'
require 'gene_by_gene/models/update_notification_subscription_command'
require 'gene_by_gene/models/xad'
require 'gene_by_gene/models/xcn'
require 'gene_by_gene/models/xon'
require 'gene_by_gene/models/xpn'
require 'gene_by_gene/models/xtn'

# APIs
require 'gene_by_gene/api/attributes_api'
require 'gene_by_gene/api/ehr_api'
require 'gene_by_gene/api/event_types_api'
require 'gene_by_gene/api/fulfillments_api'
require 'gene_by_gene/api/kit_order_lines_api'
require 'gene_by_gene/api/kits_api'
require 'gene_by_gene/api/notification_subscriptions_api'
require 'gene_by_gene/api/order_lines_api'
require 'gene_by_gene/api/orders_api'
require 'gene_by_gene/api/products_api'
require 'gene_by_gene/api/results_api'

module GeneByGene
  class << self
    # Customize default settings for the SDK using block.
    #   GeneByGene.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
